version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_backend
    environment:
      - PYTHONPATH=/app
    ports:
      - "5001:5001"
    env_file:
      - ./env/.env
    volumes:
      - ./backend/app:/app           # source code
      # - ./backend/data:/app/data # mount folder สำหรับ backup file
    networks:
      - app-network
    restart: unless-stopped
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5001", "--reload"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "5000:5000"
    env_file:
      - ./env/.env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
