CREATE TABLE BMA_PHASE_II.BLACKLISTS (
	id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	department_id NUMBER NOT NULL,
	license_plate varchar2(50),
	plate_province varchar2(100),
	color varchar2(100),
	type varchar2(100),
	note varchar2(500),
	created_date DATE NOT NULL,
	CONSTRAINT fk_department_id_blacklist
		FOREIGN KEY (department_id)
		REFERENCES BMA_PHASE_II.DEPARTMENTS(id)
		ON DELETE CASCADE
);

CREATE TABLE BMA_PHASE_II.BLACKLISTS_PASSING (
	id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	blacklist_id NUMBER NOT NULL,
	pass_id varchar2(64),
	plate_url varchar2(200),
	image_url varchar2(200),
	plate_no varchar2(50),
	province varchar2(100),
	checkpoint varchar2(100),
	latitude varchar2(12),
	longtitude varchar2(12),
	direction varchar2(12),
	pass_time TIMESTAMP,
	type varchar2(100),
	color varchar2(100),
	rtsp_url varchar2(200),
	CONSTRAINT fk_blacklist_id_blacklist_passing
		FOREIGN KEY (blacklist_id)
		REFERENCES BMA_PHASE_II.BLACKLISTS(id)
		ON DELETE CASCADE
);