CREATE TABLE BMA_PHASE_II.TRUCKS_PASSING (
	id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	pass_id varchar2(64),
	plate_url varchar2(200),
	image_url varchar2(200),
	plate_no varchar2(50),
	province varchar2(100),
	checkpoint varchar2(100),
	latitude varchar2(12),
	longtitude varchar2(12),
	direction varchar2(12),
	pass_time TIMESTAMP,
	type varchar2(100),
	color varchar2(100),
	rtsp_url varchar2(200)
);