# Generated by Django 4.1 on 2022-11-05 1:51

from django.db import migrations
import json

class Migration(migrations.Migration):

    dependencies = [
        ('api', '00014_seed_menu_config'),
    ]

    operations = [
        ## seed permission
        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.PERMISSIONS (user_level_id, menu_id)
            VALUES (1, 1);
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.PERMISSIONS (user_level_id, menu_id)
            VALUES (1, 2);
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.PERMISSIONS (user_level_id, menu_id)
            VALUES (1, 3);
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.PERMISSIONS (user_level_id, menu_id)
            VALUES (1, 4);
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.PERMISSIONS (user_level_id, menu_id)
            VALUES (1, 5);
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.PERMISSIONS (user_level_id, menu_id)
            VALUES (1, 6);
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.PERMISSIONS (user_level_id, menu_id)
            VALUES (1, 7);
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.PERMISSIONS (user_level_id, menu_id)
            VALUES (1, 8);
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.PERMISSIONS (user_level_id, menu_id)
            VALUES (1, 9);
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.PERMISSIONS (user_level_id, menu_id)
            VALUES (1, 10);
        '''),
    ]