# Generated by Django 4.1 on 2022-10-12 15:01

from django.db import migrations
import os

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_seed_time_range_config'),
    ]

    execute_path = os.getcwd()
    migration_sql_config = r'api/migrationSQL'
    migration_sql_path = os.path.join(execute_path, migration_sql_config)

    truck_config = 'truck_config.sql'
    truck_config_path = os.path.join(migration_sql_path, truck_config)
    truck_config_sql = open(truck_config_path).read()

    operations = [
        migrations.RunSQL(truck_config_sql)
    ]
