# Generated by Django 4.1 on 2022-11-05 1:51

from django.db import migrations
import json

class Migration(migrations.Migration):

    dependencies = [
        ('api', '00012_alter_table_menu_name_config'),
    ]

    ## menu
    menu_child_objs = {
        'installing': [
            {
                'checkpoints_data': True,
                'path': '/installing'
            }
        ],
        'device_status': [
            {
                'checkpoints_data': True,
                'path': '/device-status'
            }
        ],
        'search_vehicle': [
            {
                'name': "เพิ่มข้อมูลยานพาหนะที่กำหนด",
                'path': "/vehicle/add",
                'is_checkpoint': False,
                'child_obj': []
            },
            {
                'name': "ข้อมูลยานพาหนะที่กำหนด",
                'path': "/vehicle/list-blacklist",
                'is_checkpoint': False,
                'child_obj': []
            },
            {
                'name': "ค้นหาข้อมูลยานพาหนะที่กำหนด",
                'path': "/vehicle/search-blacklist",
                'is_checkpoint': False,
                'child_obj': []
            }
        ],
        'search_vehicle_violation': [
            {
                'name': "ค้นหายานพาหนะ",
                'path': "/vehicle/search",
                'is_checkpoint': False,
                'child_obj': []
            },
            {
                'name': "ค้นหาข้อมูลยานพาหนะที่ฝ่าฝืนสัญญาณไฟจราจรทางข้ามชนิดปุ่มกด",
                'path': "/vehicle/search-violation",
                'is_checkpoint': False,
                'child_obj': []
            },
            {
                'name': "ค้นหาข้อมูลรถบรรทุกในช่วงเวลาที่ห้ามเดินรถ",
                'path': "/vehicle/list-truck",
                'is_checkpoint': False,
                'child_obj': []
            }
        ],
        'traffic': [
            {
                'name': "ดูสภาพการจราจร",
                'path': "/traffic/present",
                'is_checkpoint': False,
                'child_obj': [
                    {
                        'checkpoints_data': True,
                        'path': '/traffic/present'
                    }
                ]
            },
            {
                'name': "ดูสภาพการจราจรย้อนหลัง",
                'path': "/traffic/belated",
                'is_checkpoint': False,
                'child_obj': [
                    {
                        'checkpoints_data': True,
                        'path': '/traffic/belated'
                    }
                ]
            }
        ],
        'user_management': [
            {
                'name': "จัดการผู้ใช้งาน",
                'path': "/user-management",
                'is_checkpoint': False,
                'child_obj': []
            },
            {
                'name': "จัดการกลุ่มผู้ใช้งาน",
                'path': "/group-management",
                'is_checkpoint': False,
                'child_obj': []
            },
            {
                'name': "จัดการสิทธิการเข้าใช้งาน",
                'path': "/permission-management",
                'is_checkpoint': False,
                'child_obj': []
            },
            {
                'name': "จัดการจุดติดตั้ง",
                'path': "/installation-management",
                'is_checkpoint': False,
                'child_obj': []
            },
            {
                'name': "จัดการกล้อง",
                'path': "/camera-management",
                'is_checkpoint': False,
                'child_obj': []
            },
            {
                'name': "จัดการถนน",
                'path': "/road-management",
                'is_checkpoint': False,
                'child_obj': []
            },
            {
                'name': "จัดการถนนรอง",
                'path': "/secondary-road-management",
                'is_checkpoint': False,
                'child_obj': []
            },
            {
                'name': "จัดการเลนถนน",
                'path': "/road-lane-management",
                'is_checkpoint': False,
                'child_obj': []
            },
            {
                'name': "จัดการอัพเดทรายงาน",
                'path': "/update-list-management",
                'is_checkpoint': False,
                'child_obj': []
            }
        ],
    }

    operations = [
        ## seed menu
        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.MENUS (name, path, child_obj, for_super_user)
            VALUES ('หน้าหลัก', '/dashboard', '[]', 0);
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.MENUS (name, path, child_obj, for_super_user)
            VALUES ('จุดติดตั้ง', '/installing', '{}', 0);
        '''.format(json.dumps(menu_child_objs['installing'], ensure_ascii=False).encode('utf8').decode())),

         migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.MENUS (name, path, child_obj, for_super_user)
            VALUES ('รายงานข้อมูลจราจร', '/traffic-detail', '[]', 0);
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.MENUS (name, path, child_obj, for_super_user)
            VALUES ('ข้อมูลยานพาหนะที่กำหนด', '/vehicle/add', '{}', 0);
        '''.format(json.dumps(menu_child_objs['search_vehicle'], ensure_ascii=False).encode('utf8').decode())),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.MENUS (name, path, child_obj, for_super_user)
            VALUES ('ข้อมูลยานพาหนะ', '/vehicle/search', '{}', 0);
        '''.format(json.dumps(menu_child_objs['search_vehicle_violation'], ensure_ascii=False).encode('utf8').decode())),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.MENUS (name, path, child_obj, for_super_user)
            VALUES ('ข้อมูลจุดต้นทาง/ปลายทางของยานพาหนะ', '/origin-destination', '[]', 0);
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.MENUS (name, path, child_obj, for_super_user)
            VALUES ('ดูสภาพการจราจร', '/traffic/present', '{}', 0);
        '''.format(json.dumps(menu_child_objs['traffic'], ensure_ascii=False).encode('utf8').decode())),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.MENUS (name, path, child_obj, for_super_user)
            VALUES ('รายงานสถานะอุปกรณ์', '/device-status', '[]', 0);
        '''.format(json.dumps(menu_child_objs['device_status'], ensure_ascii=False).encode('utf8').decode())),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.MENUS (name, path, child_obj, for_super_user)
            VALUES ('รายงานผลข้อมูลจราจรของ กทม.', '/report-bkk', '[]', 0);
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.MENUS (name, path, child_obj, for_super_user)
            VALUES ('System Configuration', '/user-management', '[]', 1);
        '''.format(json.dumps(menu_child_objs['user_management'], ensure_ascii=False).encode('utf8').decode())),
    ]

