# Generated by Django 4.1 on 2022-10-17 14:57

from django.db import migrations
import os


class Migration(migrations.Migration):

    dependencies = [
        ('api', '00010_init_truckpassing_config'),
    ]

    execute_path = os.getcwd()
    migration_sql_config = r'api/migrationSQL'
    migration_sql_path = os.path.join(execute_path, migration_sql_config)

    record_config = 'violation_config.sql'
    record_config_path = os.path.join(migration_sql_path, record_config)
    record_config_sql = open(record_config_path).read()

    operations = [
        migrations.RunSQL(record_config_sql)
    ]