# Generated by Django 4.1 on 2022-08-08 12:25

from django.db import migrations
import os

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    execute_path = os.getcwd()
    migration_sql_config = r'api/migrationSQL'
    migration_sql_path = os.path.join(execute_path, migration_sql_config)

    group_config = 'group_config.sql'
    group_config_path = os.path.join(migration_sql_path, group_config)
    group_config_sql = open(group_config_path).read()

    operations = [
        migrations.RunSQL(group_config_sql)
    ]
