# Generated by Django 4.1 on 2022-11-05 1:51

from django.db import migrations
import json

class Migration(migrations.Migration):

    dependencies = [
        ('api', '00016_alter_table_user_detail_config'),
    ]

    ## menu
    menu_child_objs = {
        'device_status': [
            {
                'checkpoints_data': True,
                'path': '/device-status'
            }
        ]
    }

    operations = [
        ## seed menu

        migrations.RunSQL('''
            UPDATE BMA_PHASE_II.MENUS SET child_obj = '{}' WHERE name = 'รายงานสถานะอุปกรณ์';
        '''.format(json.dumps(menu_child_objs['device_status'], ensure_ascii=False).encode('utf8').decode())),
    ]

