# Generated by Django 4.1 on 2022-08-08 17:57

from django.db import migrations
import os

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_init_group_config'),
    ]

    execute_path = os.getcwd()
    migration_sql_config = r'api/migrationSQL'
    migration_sql_path = os.path.join(execute_path, migration_sql_config)

    user_config = 'user_config.sql'
    user_config_path = os.path.join(migration_sql_path, user_config)
    user_config_sql = open(user_config_path).read()

    operations = [
        migrations.RunSQL(user_config_sql)
    ]
