# Generated by Django 4.1 on 2022-12-01 15:01

from django.db import migrations
import os

class Migration(migrations.Migration):

    dependencies = [
        ('api', '00020_alter_table_blacklist_passing_config'),
    ]

    execute_path = os.getcwd()
    migration_sql_config = r'api/migrationSQL'
    migration_sql_path = os.path.join(execute_path, migration_sql_config)

    group_name_config = 'group_name_config.sql'
    group_name_config_path = os.path.join(migration_sql_path, group_name_config)
    group_name_config_sql = open(group_name_config_path).read()

    operations = [
        migrations.RunSQL(group_name_config_sql)
    ]