# Generated by Django 4.1 on 2022-12-01 15:01

from django.db import migrations
import os

class Migration(migrations.Migration):

    dependencies = [
        ('api', '00019_alter_table_destination_total_config'),
    ]

    execute_path = os.getcwd()
    migration_sql_config = r'api/migrationSQL'
    migration_sql_path = os.path.join(execute_path, migration_sql_config)

    blacklist_config = 'blacklist_status_config.sql'
    blacklist_config_path = os.path.join(migration_sql_path, blacklist_config)
    blacklist_config_sql = open(blacklist_config_path).read()

    operations = [
        migrations.RunSQL(blacklist_config_sql)
    ]