# Generated by Django 4.1 on 2022-10-11 16:02

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_init_permission_config'),
    ]

    operations = [
        ## seed department
        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.DEPARTMENTS (name)
            VALUES ('ผู้ควบคุมงาน/หัวหน้าฝ่าย');
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.DEPARTMENTS (name)
            VALUES ('ผอ.กอง/สำนัก/ผู้ว่า');
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.DEPARTMENTS (name)
            VALUES ('บก.02');
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.DEPARTMENTS (name)
            VALUES ('สถานีตำรวจในท้องที่');
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.DEPARTMENTS (name)
            VALUES ('หน่วยงานภายนอกอื่นๆ');
        '''),

        ## seed user level
        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.USER_LEVELS (name)
            VALUES ('สูง')
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.USER_LEVELS (name)
            VALUES ('ปานกลางค่อนสูง')
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.USER_LEVELS (name)
            VALUES ('ปานกลาง')
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.USER_LEVELS (name)
            VALUES ('ต่ำค่อนปานกลาง')
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.USER_LEVELS (name)
            VALUES ('ต่ำ')
        '''),

        ## seed group
        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.GROUPS (DEPARTMENT_ID, USER_LEVEL_ID)
            VALUES (1, 1)
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.GROUPS (DEPARTMENT_ID, USER_LEVEL_ID)
            VALUES (2, 1)
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.GROUPS (DEPARTMENT_ID, USER_LEVEL_ID)
            VALUES (3, 1)
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.GROUPS (DEPARTMENT_ID, USER_LEVEL_ID)
            VALUES (4, 1)
        '''),

        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.GROUPS (DEPARTMENT_ID, USER_LEVEL_ID)
            VALUES (5, 1)
        '''),
    ]
