# Generated by Django 4.1 on 2022-10-11 16:37

from django.db import migrations
from argon2 import PasswordHasher

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_seed_group_config'),
    ]

    username = 'system'
    password = 'BmaTraffic@1234#'

    ph = PasswordHasher()
    hash = ph.hash(password)

    operations = [
        migrations.RunSQL('''
            INSERT INTO BMA_PHASE_II.USERS (NAME, PASSWORD, GROUP_ID, IS_SUPER_USER)
            VALUES ('{}', '{}', {}, 1)
        '''.format(username, hash, 1)),
    ]
