# Generated by Django 4.1 on 2022-10-17 14:56

from django.db import migrations
import os


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_init_blacklist_config'),
    ]

    execute_path = os.getcwd()
    migration_sql_config = r'api/migrationSQL'
    migration_sql_path = os.path.join(execute_path, migration_sql_config)

    time_range_config = 'time_range_config.sql'
    time_range_config_path = os.path.join(migration_sql_path, time_range_config)
    time_range_config_sql = open(time_range_config_path).read()

    operations = [
        migrations.RunSQL(time_range_config_sql)
    ]