# Generated by Django 4.1 on 2022-10-17 15:00

from django.db import migrations
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_init_record_config'),
    ]

    sql_insert_command = 'INSERT ALL '
    init_time = datetime.datetime.strptime('00:00', '%H:%M')
    insert_values = ''

    for i in range(288):
        time_range_id = i + 1
        start = i * 5
        end = (i + 1) * 5

        start_time_append = datetime.timedelta(minutes=start)
        end_time_append = datetime.timedelta(minutes=end)

        start_time = init_time + start_time_append
        end_time = init_time + end_time_append

        data_command = """
        INTO BMA_PHASE_II.TIME_RANGES (ID, START_TIME, END_TIME) VALUES ({}, '{}', '{}')
        """.format(time_range_id, start_time.strftime('%H:%M'), end_time.strftime('%H:%M'))

        sql_insert_command += data_command

    insert_endline_command = 'SELECT * FROM DUAL'
    sql_insert_command += insert_endline_command

    operations = [
        migrations.RunSQL(sql_insert_command)
    ]
