# Generated by Django 4.1 on 2025-05-21 09:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '00021_alter_table_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(default=None, max_length=10, null=True)),
                ('plate_province', models.CharField(default=None, max_length=75, null=True)),
                ('color', models.CharField(default=None, max_length=30, null=True)),
                ('type', models.CharField(default=None, max_length=50, null=True)),
                ('note', models.CharField(default=None, max_length=500, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'blacklists',
            },
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(default=None, max_length=100, null=True)),
                ('child_obj', models.JSONField(default=list)),
                ('for_super_user', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'menus',
            },
        ),
        migrations.CreateModel(
            name='TimeRangeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.CharField(max_length=5)),
                ('end_time', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'time_ranges',
            },
        ),
        migrations.CreateModel(
            name='TruckPassingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_id', models.CharField(max_length=64, null=True)),
                ('plate_url', models.CharField(max_length=200, null=True)),
                ('image_url', models.CharField(max_length=200, null=True)),
                ('plate_no', models.CharField(max_length=20, null=True)),
                ('province', models.CharField(max_length=50, null=True)),
                ('checkpoint', models.CharField(max_length=80, null=True)),
                ('latitude', models.CharField(max_length=12, null=True)),
                ('longtitude', models.CharField(max_length=12, null=True)),
                ('direction', models.CharField(max_length=12, null=True)),
                ('pass_time', models.DateTimeField(null=True)),
                ('type', models.CharField(max_length=24, null=True)),
                ('color', models.CharField(max_length=12, null=True)),
                ('rtsp_url', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'trucks_passing',
            },
        ),
        migrations.CreateModel(
            name='ViolationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checkpoint_id', models.IntegerField(default=None)),
                ('direction', models.CharField(choices=[('IN', 'In Bound'), ('OUT', 'Out Bound')], default='IN', max_length=3)),
                ('car_type_id', models.IntegerField(default=None)),
                ('volume', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.timerangemodel')),
            ],
            options={
                'db_table': 'violation_records',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('is_super_user', models.BooleanField(default=False)),
                ('group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.groupmodel')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='RecordModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checkpoint_id', models.IntegerField(default=None)),
                ('direction', models.CharField(choices=[('IN', 'In Bound'), ('OUT', 'Out Bound')], default='IN', max_length=3)),
                ('car_type_id', models.IntegerField(default=None)),
                ('volume', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.timerangemodel')),
            ],
            options={
                'db_table': 'records',
            },
        ),
        migrations.CreateModel(
            name='PermissionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.groupmodel')),
                ('menu', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.menumodel')),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usermodel')),
            ],
            options={
                'db_table': 'logins',
            },
        ),
        migrations.CreateModel(
            name='BlacklistPassingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_id', models.CharField(max_length=64, null=True)),
                ('plate_url', models.CharField(max_length=200, null=True)),
                ('image_url', models.CharField(max_length=200, null=True)),
                ('plate_no', models.CharField(max_length=20, null=True)),
                ('province', models.CharField(max_length=50, null=True)),
                ('checkpoint', models.CharField(max_length=80, null=True)),
                ('latitude', models.CharField(max_length=12, null=True)),
                ('longtitude', models.CharField(max_length=12, null=True)),
                ('direction', models.CharField(max_length=12, null=True)),
                ('pass_time', models.DateTimeField(null=True)),
                ('type', models.CharField(max_length=24, null=True)),
                ('color', models.CharField(max_length=12, null=True)),
                ('rtsp_url', models.CharField(max_length=200, null=True)),
                ('blacklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.blacklistmodel')),
            ],
            options={
                'db_table': 'blacklists_passing',
            },
        ),
        migrations.AddField(
            model_name='blacklistmodel',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.groupmodel'),
        ),
    ]
