from api.models.group import GroupModel
from api.models.menu import MenuModel
from api.models.permission import PermissionModel
from api.models.record import RecordModel
from api.models.timeRange import TimeRangeModel
from api.models.user import UserModel
from api.models.login import LoginModel
from api.models.blacklist import BlacklistModel
from api.models.blacklistPassing import BlacklistPassingModel
from api.models.truckPassing import TruckPassingModel